apiVersion: v1
kind: apic.ibm.com/APIConnectCluster
metadata:
  creationTimestamp: "2018-10-24T20:37:09Z"
  name: apiconnect
spec:
  secret-name: apiconnect
  subsystems:
  - apiVersion: v1
    kind: apic.ibm.com/ManagementSubsystem
    metadata:
      creationTimestamp: "2018-10-24T20:37:09Z"
      name: manager
    spec:
      ApplianceProperties: null
      CloudProperties:
        ingress-type: ingress
        mode: dev
        namespace: apic
        registry: apic-dev-docker-local.artifactory.swg-devops.com/apicup-imgs/2018.4.1-3492
        registry-secret: apiconnect-image-pull-secret
        storage-class: ibmc-block-gold
      SubsystemProperties:
        secret-name: apiconnect-manager
        target: kubernetes
      endpoints:
        api-manager-ui: manager.apic2018.tor01.containers.appdomain.cloud
        cloud-admin-ui: cloud.apic2018.tor01.containers.appdomain.cloud
        consumer-api: consumer.apic2018.tor01.containers.appdomain.cloud
        platform-api: platform.apic2018.tor01.containers.appdomain.cloud
      settings:
        cassandra-backup-path: /backups
        cassandra-backup-port: 22
        cassandra-backup-protocol: sftp
        cassandra-backup-schedule: 0 0 * * *
        cassandra-cluster-size: 3
        cassandra-max-memory-gb: 8
        cassandra-postmortems-path: /cassandra-postmortems
        cassandra-postmortems-port: 22
        cassandra-volume-size-gb: 16
        create-crd: true
    status: {}
  - apiVersion: v1
    kind: apic.ibm.com/PortalSubsystem
    metadata:
      creationTimestamp: "2018-10-24T20:37:09Z"
      name: portal
    spec:
      ApplianceProperties: null
      CloudProperties:
        ingress-type: ingress
        mode: dev
        namespace: apic
        registry: apic-dev-docker-local.artifactory.swg-devops.com/apicup-imgs/2018.4.1-3492
        registry-secret: apiconnect-image-pull-secret
        storage-class: ibmc-block-gold
      SubsystemProperties:
        secret-name: apiconnect-portal
        target: kubernetes
      endpoints:
        portal-admin: portal-admin.apic2018.tor01.containers.appdomain.cloud
        portal-www: portal.apic2018.tor01.containers.appdomain.cloud
      settings:
        admin-storage-size-gb: 1
        backup-storage-size-gb: 5
        db-logs-storage-size-gb: 2
        db-storage-size-gb: 12
        site-backup-host: ""
        site-backup-path: /site-backups
        site-backup-port: 22
        www-storage-size-gb: 5
    status: {}
  - apiVersion: v1
    kind: apic.ibm.com/GatewaySubsystem
    metadata:
      creationTimestamp: "2018-10-24T20:37:09Z"
      name: apigateway
    spec:
      ApplianceProperties: null
      CloudProperties:
        extra-values-file: gw-extras.yaml
        ingress-type: ingress
        mode: dev
        namespace: apic
        registry-secret: apiconnect-image-pull-secret
        storage-class: ibmc-block-gold
      SubsystemProperties:
        secret-name: apiconnect-apigateway
        target: kubernetes
      endpoints:
        api-gateway: apigateway.apic2018.tor01.containers.appdomain.cloud
        apic-gw-service: apigateway-service.apic2018.tor01.containers.appdomain.cloud
      settings:
        enable-high-performance-peering: "true"
        enable-tms: false
        image-pull-policy: Always
        image-repository: apic-dev-docker-local.artifactory.swg-devops.com/apiconnect/datapower-api-gateway
        image-tag: latest
        monitor-image-repository: apic-dev-docker-local.artifactory.swg-devops.com/k8s-datapower-monitor
        monitor-image-tag: latest
        max-cpu: 4
        max-memory-gb: 6
        replica-count: 1
        tms-peering-storage-size-gb: 10
        v5-compatibility-mode: false
    status: {}
  - apiVersion: v1
    kind: apic.ibm.com/AnalyticsSubsystem
    metadata:
      creationTimestamp: "2018-10-24T20:37:09Z"
      name: analytics
    spec:
      ApplianceProperties: null
      CloudProperties:
        extra-values-file: analytics-extras.yaml
        ingress-type: ingress
        mode: dev
        namespace: apic
        registry: apic-dev-docker-local.artifactory.swg-devops.com/apicup-imgs/2018.4.1-3492
        registry-secret: apiconnect-image-pull-secret
        storage-class: ibmc-block-gold
      SubsystemProperties:
        secret-name: apiconnect-analytics
        target: kubernetes
      endpoints:
        analytics-client: ac.apic2018.tor01.containers.appdomain.cloud
        analytics-ingestion: ai.apic2018.tor01.containers.appdomain.cloud
      settings:
        coordinating-max-memory-gb: 6
        data-max-memory-gb: 6
        data-storage-size-gb: 200
        master-max-memory-gb: 6
        master-storage-size-gb: 5
    status: {}
status:
  Ready: false
